# Generated by Django 2.2.5 on 2019-12-03 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='password',
            new_name='yubikey_id',
        ),
    ]
