# Generated by Django 2.2.5 on 2019-12-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20191203_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='yubikey_id',
            field=models.CharField(max_length=45),
        ),
    ]
