# Generated by Django 2.2.5 on 2019-12-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20191203_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(default='asd', max_length=45),
            preserve_default=False,
        ),
    ]
