# Generated by Django 3.0.2 on 2020-01-31 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('story', models.CharField(max_length=2000)),
                ('is_beginning', models.BooleanField()),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_continuation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continuation', to='menu.Story')),
                ('fk_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='menu.Story')),
            ],
        ),
    ]
