# Generated by Django 2.2.5 on 2020-01-27 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200122_1048'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='fk_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.User'),
            preserve_default=False,
        ),
    ]
