# Generated by Django 2.2.5 on 2020-01-29 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_story_fk_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='is_beginning',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='story',
            name='story',
            field=models.CharField(max_length=2000),
        ),
    ]
