# Generated by Django 2.2.5 on 2020-01-29 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200129_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_continuation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continuation', to='menu.Story')),
                ('fk_origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='menu.Story')),
            ],
        ),
    ]
